name: Linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

  markdown-link-check:
    name: LinkCheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: umbrelladocs/action-linkspector@v1